version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - cool_network 
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:latest
    env_file: .env

    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
    networks:
      - cool_network
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

volumes:
  postgres_data_new:

networks:
  cool_network: